### ISSUE TITLE
Set up new GitHub repository

### ISSUE THREAD

**Issue by DanaMurali** [DanaMurali/The_Chiron_Project_2#1]
### Tasks

- [x] Create new repository
- [ ] Set up configuration for new repo
- [x] Add GitHub project to new repo
- [x] Generate new codebase using `create-t3-app` or `create-t3-turbo`
