### ISSUE TITLE
Add entity relationship diagram

### ISSUE THREAD

**Issue by Djontleman** [DanaMurali/The_Chiron_Project_2#3]
### Feature
Add entity relationship diagram using diagram.io

### Tasks
- [x] Make new branch (`diagram-io`)
- [ ] Authorise diagram.io for repository
- [ ] Add diagram to `diagram-io` branch
- [ ] Make entity relationship diagram
